// AUTO-GENERATED BY PYRO (Q16.16)
package bayesian_params_pkg;
    localparam signed [31:0] MODEL_M     = 32'sd261561;
    localparam signed [31:0] MODEL_B     = 32'sd-661607;
    localparam signed [31:0] MODEL_SIGMA = 32'sd546108;
endpackage
