import torch
import pyro
import pyro.distributions as dist
from pyro.infer import SVI, Trace_ELBO, Predictive
from pyro.optim import Adam
from pyro.infer.autoguide import AutoDiagonalNormal
import matplotlib.pyplot as plt

# ==========================================
# 1. Dummy-Daten generieren (Sensordaten etc.)
# ==========================================
torch.manual_seed(42)
x = torch.linspace(-20, 20, 100)
y_true = 4 * x - 10
y = y_true + torch.randn(100) * 10.0 # Rauschen hinzufügen

# ==========================================
# 2. Pyro Modell definieren
# ==========================================
def model(x, y=None):
    m = pyro.sample("m", dist.Normal(0.0, 10.0))
    b = pyro.sample("b", dist.Normal(0.0, 10.0))
    sigma = pyro.sample("sigma", dist.HalfNormal(10.0))
    
    mu = m * x + b
    
    with pyro.plate("data", len(x)):
        pyro.sample("obs", dist.Normal(mu, sigma), obs=y)

# ==========================================
# 3. Modell Trainieren (SVI)
# ==========================================
print("Starte Training...")
guide = AutoDiagonalNormal(model) 
adam = Adam({"lr": 0.05})
svi = SVI(model, guide, adam, loss=Trace_ELBO())

pyro.clear_param_store()
for epoch in range(1500):
    loss = svi.step(x, y)
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | Loss: {loss:.2f}")

# ==========================================
# 4. Posterior Predictive Sampling (Für die Grafik)
# ==========================================
print("\nGeneriere Grafik...")
# Wir ziehen 1000 Samples aus unserem trainierten Modell
predictive = Predictive(model, guide=guide, num_samples=1000, return_sites=("m", "b"))
samples = predictive(x)

# Berechne mu für jedes der 1000 Samples: mu = m * x + b
m_samples = samples["m"].squeeze()
b_samples = samples["b"].squeeze()
mu_samples = m_samples.unsqueeze(1) * x.unsqueeze(0) + b_samples.unsqueeze(1)

# Durchschnitt und Standardabweichung der Vorhersagen berechnen
mu_mean = mu_samples.mean(dim=0).detach()
mu_std = mu_samples.std(dim=0).detach()

# ==========================================
# 5. Plotten (Analog zu deinem Screenshot)
# ==========================================
plt.figure(figsize=(10, 6))

# 1. Generative function (Das wahre Modell)
plt.plot(x.numpy(), y_true.numpy(), color='grey', linestyle='dashed', alpha=0.7, label='Generative function')

# 2. Observations (Die verrauschten Datenpunkte)
plt.scatter(x.numpy(), y.numpy(), color='grey', s=15, label='Observations')

# 3. Unsicherheits-Bänder (Grüne Bereiche für 1 und 2 Standardabweichungen)
# Helles Grün (ca. 95% Konfidenz)
plt.fill_between(x.numpy(), 
                 (mu_mean - 1.96 * mu_std).numpy(), 
                 (mu_mean + 1.96 * mu_std).numpy(), 
                 color='green', alpha=0.2, label='m - Uncertainty (95%)')
# Dunkleres Grün (ca. 68% Konfidenz)
plt.fill_between(x.numpy(), 
                 (mu_mean - mu_std).numpy(), 
                 (mu_mean + mu_std).numpy(), 
                 color='green', alpha=0.4)

# 4. Model - mu (Unsere trainierte Mittelwert-Vorhersage)
plt.plot(x.numpy(), mu_mean.numpy(), color='red', linestyle='dashed', linewidth=1.5, label='Model - mu')

# Layout hübsch machen
plt.xlabel("x")
plt.ylabel("y")
plt.title("Bayesian Linear Regression - Posterior Predictive")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()

# Grafik anzeigen (und/oder speichern)
plt.savefig("bayesian_regression_plot.png", dpi=300)
plt.show()

# ==========================================
# 6. FPGA Vorbereitung (Wie zuvor)
# ==========================================
quantiles = guide.quantiles([0.5]) 
m_fpga = int(quantiles['m'][0].item() * (1 << 16))
b_fpga = int(quantiles['b'][0].item() * (1 << 16))
sigma_fpga = int(quantiles['sigma'][0].item() * (1 << 16))

sv_code = f"""// AUTO-GENERATED BY PYRO (Q16.16)
package bayesian_params_pkg;
    localparam signed [31:0] MODEL_M     = 32'sd{m_fpga};
    localparam signed [31:0] MODEL_B     = 32'sd{b_fpga};
    localparam signed [31:0] MODEL_SIGMA = 32'sd{sigma_fpga};
endpackage
"""
with open("bayesian_params_pkg.sv", "w") as f:
    f.write(sv_code)
print("\nSystemVerilog Package generiert!")